#----------------------------------------------------------------------
# Logging Configuration File Path
#----------------------------------------------------------------------
logging:
  config: classpath:config/log-local.xml